export const mode = {
  topic: 'topic',
  interview: 'interview',
  interviewPosition: 'interviewPosition',
  scenario: 'scenario',
};

const settings = {
  practiceLanguage: 'English',
  languageLevel: 'Intermediate',
  mode: mode.topic,
  topics: [],
  interview: {
    position: '',
    isPosition: false,
  },
  selectedTopic: '',
  maxDayFreeCost: 0.14,
  maxDayPaidCost: 0.29,
  maxDaysTrial: 3,
  maxDayFreeFeedback: 1,
};

export const userData = {
  from: {},
  premium: false,
  dayCost: 0,
  dailyCost: [],
  monthCost: 0,
  trialDays: 0,
  dayFreeFeedback: 0,
  lastPremiumDate: '',
  lastTrialDate: '',
  canWeWrite: null,
  userTextMessages: 0,
  userAudioMessages: 0,
  scenarioGoals: {},
  currentScenariosPage: 1,
  messagesHistory: [],
};

export const INITIAL_SESSION = {
  messages: [],
  settings,
  lastCheckMessage: {},
  diffText: '',
  pronounce: {},
  lastResponse: '',
  lastUserMessage: '',
  pronounseScores: [],
  grammarScores: [],
  averagePronunciationScore: 0,
  averageGrammarScore: 0,
  userData,
  currentScenarioIndex: 0,
  currentScenarioGoals: [false, false, false, false],
  maxScenariosPage: 2,
};

export const prices = {
  'gpt-3.5-turbo-1106': {
    prompt: 0.000001,
    completion: 0.000002,
  },
  'gpt-4-1106-preview': {
    prompt: 0.00001,
    completion: 0.00003,
  },
  'whisper-1': {
    audio: 0.0001,
  },
  tts: {
    text: 0.000015,
  },
  'pronunciation-assessment': {
    audio: 0.00042,
  },
};

export const ERROR_MESSAGE = 'Ooops. Please try again or /start.';

export const scenarios = [
  {
    title: '🧑‍🎓️ First day of class',
    description:
      'You are studying at an American university. When you entered the classroom on the first day of class, a friendly student sat next you and started talking to you.',
    prompt:
      "Your name is Alex and you're in a psychology class. You are an outgoing, sociable student at an American university. Spotting a new face in class today, you decide to make them feel welcome by striking up a conversation and introducing yourself.",
    goals: [
      'Introduce yourself to your classmate.',
      'Talk about where you are from and what you study.',
      'Tell the student that she looks prepared for class.',
      'Ask the student if she has any advice about the class.',
    ],
    hints: [
      'Where are you from?',
      'What do you study?',
      "I'm majoring in Biology.",
      "It looks like you're really organized.",
      'See you around!',
    ],
  },
  {
    title: '🍕 Order pizza delivery',
    description: 'You are coming to New York. Call the pizzeria and ask for pizza delivery.',
    prompt:
      "Your name is Maria and you work for the company BestPizza, which is based in New York. You answer a customer's phone call about a pizza order. Start by introducing yourself and clarifying what you can do to help.",
    goals: [
      'Order a pizza.',
      "Make sure there's no onion on your pizza.",
      'Ask about delivery time',
      'Ask for appetizer recommendation.',
    ],
    hints: [
      "I'd like to order a pizza for delivery.",
      'No onion, please.',
      'Do you have any specials?',
      'What appetizers would you recommend?',
      'How long will that take?',
    ],
  },
  {
    title: '🍣 Sushi party with colleagues',
    description:
      'On Friday night, your colleagues and you decided to meet at a sushi restaurant. Call the store, talk to the store manager, and reserve a seat.',
    prompt:
      'Your name is Linda and you work for the company TastySushi. As the store manager at a sushi restaurant, answer the call promptly and assist the customer with their reservation request. Ensure to inquire about the number of people in the party and ask if there are any special accommodations that might be needed. Provide a warm confirmation and let them know you look forward to welcoming them to the establishment.',
    goals: [
      'Make a dinner reservation',
      'Ask if they have any availability for Friday at 6pm.',
      'Ask if they have a table for 6 to 8 people.',
      'Ask what kind of beer or sake they offer.',
    ],
    hints: [
      "I'd like to make a reservation.",
      'Do you have any availability for Friday at 6pm?',
      'Do you have a table for 8 people?',
      'What kind of beer and sake do you have?',
      'Looking forward to it!',
    ],
  },
  {
    title: '🛎 Long stay hotel',
    description:
      "You're going to Orlando, Florida on a business trip for 3 weeks and decided to stay at an extended stay hotel. Arrive at the lobby and check-in.",
    prompt:
      'Your name is Susan and you work for the company ComfyHotel. You work at the front desk of an extended stay hotel in Orlando, Florida. A guest has just walked in, greet the guest warmly.',
    goals: [
      'Check in and get the room key.',
      'Ask if room service is available or there is a kitchen in the hotel room.',
      'Ask if there is a convenience store or gas station nearby.',
      'Ask about shared workplaces in the hotel and ask for the wifi password.',
    ],
    hints: [
      "Hi, I'd like to check in, please.",
      'Do the rooms have kitchens or is there a room service?',
      'Is there a gas station or a convenience store nearby?',
      'Are there any workspaces here?',
      "What's the wifi password?",
    ],
  },
  {
    title: '🏘️ Neighbour',
    description:
      'You just moved into an apartment in New York. When you go outside, you bumped into someone in the next room.',
    prompt:
      "Your name is Bella. You've been living in this New York apartment building for a few years and know the ins and outs. As you hurry out to grab a morning coffee, you collide with your new neighbor, who seems a bit disoriented.",
    goals: [
      'Say hi to your neighbour and have a friendly conversation.',
      'Talk about where you are from and what you do.',
      'Tell your neighbour you like her shoes.',
      'Ask the neighbour what she think about the neighbourhood',
    ],
    hints: [
      'Hi, nice to finally meet you!',
      'I just moved here from Seoul to study English.',
      'Your shoes are awesome, but the way.',
      'Do you like living in this neighbourhood?',
      "Any cool spots you'd recommend?",
    ],
  },
  {
    title: '💼 Talk about new job',
    description:
      "You've just got a new job. You want to talk to your friend, so you meet her at the coffee shop after work.",
    prompt:
      "Your name is Judy. You're the friend who's eager to hear about my first day at work. You're already at the coffee shop, sipping your favorite drink, preparing to celebrate your friend's new beginning.",
    goals: [
      'Tell about your new job.',
      'Say something about the office',
      'Explain why you chose this job.',
      'Talk about one of your co-workers.',
    ],
    hints: [
      'I just started a new job.',
      'The office is modern and easy to get to.',
      'I chose this job because I wanted to try something new.',
      'My day usually looks like this.',
      'I have this one coworker who I really connect with.',
    ],
  },
  {
    title: '🏦 Open a bank account',
    description:
      'You are opening a new savings account at the local bank. You sit across from the bank clerk.',
    prompt:
      'Your name is Helen you work in the CityBank. You are the bank clerk. Start by saying hello and asking me what I want.',
    goals: [
      'Open a bank account.',
      'Understand the fees associated with the account.',
      'Ask about promotional offers for new accounts.',
      'Deposit money in the account.',
    ],
    hints: [
      'Can you tell me about your checking accounts?',
      'What kind of free does this account have?',
      'Do you have any promotional offers?',
      'Can I deposit money in the account right now?',
      'Thank you for your help today.',
    ],
  },
  {
    title: '👫 A new friend',
    description:
      "You were invited to a friend's party in San Francisco. You were introduced to a new person. Let's talk a lot to get to know each other.",
    prompt:
      "Your name is Eliza. You are at a social gathering in San Francisco. A mutual friend has just introduced you to someone new. You're curious to learn more about them, so you decide to engage. Start with a short introduction.",
    goals: [
      'Introduce yourself and have a casual conversation.',
      'Ask your new friend two questions about him or herself.',
      'Talk about your hometown and job in detail.',
      'Ask your new friend for a good picnic spot in San Francisco.',
    ],
    hints: [
      'So, tell me about yourself!',
      'Are you from around here?',
      'What do you do for fun?',
      'What do you do for work?',
      'Can you recommend a good picnic spot?',
    ],
  },
];

export const topics = [
  '🤖 Future of AI',
  '🌍 Climate change',
  '🚀 Space exploration',
  '🧠 Mental health',
  '👗 Fashion and trends',
  '📱 Social media impact',
  '☀️ Renewable energy',
  '🧑‍🎓️ Education',
  '🕶️ Virtual reality',
  '🔬 Genetic engineering',
  '💰 Universal basic income',
  '💱 Cryptocurrency',
  '🔒 Online privacy',
  '🖨️ 3D printing',
  '⚕️ Medical ethics',
  '⚖️ Gender equality',
  '🤖 Robotics in healthcare',
  '🏭 Automation in industry',
  '🌱 Sustainable food',
  '💧 Water scarcity',
  '👵 Aging population',
  '🎨 Digital art',
  '🌍 Cultural diversity',
  '🚀 Space tourism',
  '🚲 Sustainable transportation',
  '♻️ Renewable resources',
  '🌿 Green technology',
  '🤖 AI in healthcare',
  '✊ Social justice',
  '🧓 Aging and technology',
  '🌍 Climate action',
  '🚀 Space colonization',
  '🧬 Biotechnology',
  '👊 Cyberbullying',
  '🚯 Plastic pollution',
  '🏢 Future of work',
  '🌾 Sustainable agriculture',
  '🌐 Internet of Things',
  '💚 Ethical consumerism',
  '🎨 AI and creativity',
  '⚖️ Environmental justice',
  '🧪 Artificial life',
  '🎓 Virtual education',
  '👨‍👩‍👧‍👦 Family',
  '✈️ Travel tales',
  '🌞 Daily life',
  '🎵 Music moments',
  '🌿 Nature wonders',
  '💡 Tech trends',
  '🏥 Health matters',
  '👧🏻 Childhood memories',
  '✈️ Dream destinations',
  '📖 Life lessons',
  '🏰 Historical events',
  '🎨 Artistic flair',
  '📱 Internet trends',
  '📺 Pop culture',
  '🗓️ Weekend plans',
  '📲 Social media',
  '🗼 Famous landmarks',
  '🥗 Healthy living',
  '💑 Relationships',
  '🚀 Future plans',
  '✈️ Travel memories',
  '🏞️ Outdoor activities',
  '🎉 Cultural fests',
  '🍽️ World cuisines',
  '🌄 Adventure stories',
  '🧘 Mindful moments',
  '💼 Dream careers',
  '♻️ Sustainable living',
  '👨‍👩‍👧‍👦 Family values',
  '✈️ Travel tales',
  '🍽️ Food adventures',
  '🎯 Hobbies and interests',
  '🌍 Cultural insights',
  '💑 Relationship tips',
  '🌟 Future aspirations',
  '🎬 Movie reviews',
  '💼 Career goals',
  '🏠 Home decor',
  '🧘‍♀️ Mind-body balance',
  '📱 Tech innovations',
  '🗣️ Language tips',
  '🐾 Pet stories',
  '🔬 Science insights',
  '🌐 Virtual travel',
  '🌊 Ocean exploration',
  '🍽️ Local cuisine',
  '🏰 Historic sites',
  '👗 Fashion trends',
  '🎥 Film classics',
  '💰 Budget travel',
  '⏰ Time management',
  '🏡 Dream home',
  '📱 Mobile apps',
  '🏛️ Ancient history',
  '🛋️ Interior design',
  '🌿 Green living',
  '📚 Online learning',
  '✊ Human rights',
  '📖 Inspiring books',
  '🌌 Astronomy facts',
  '🍔 Late night impulse',
  '🥦 Healthy eating',
  '🍳 Home cooking',
  '🍔 Street food',
  '🍬 Sweet tooth',
  '🏖️ Best vacation',
  '✈️ Travel plan',
  '🧳 Business trip',
  '👫 Friends',
  '🏃‍♂️ Athlete',
  '🌟 Celebrities',
  '👪 Parents',
  '👔 Boss',
  '💑 Partner',
  '📲 Influencer',
  '🎮 Games',
  '⚽ Sports',
  '📺 TV and movies',
  '🎵 Music',
  '🏠 Hometown',
  '👶 Childhood',
  '🐶 Pet',
  '🏡 My home',
  '👨‍👩‍👧‍👦 Family events',
  '💼 Work',
  '🛍️ Shopping',
  '🎒 School',
];
