export const mode = {
  topic: 'topic',
  interview: 'interview',
  interviewPosition: 'interviewPosition',
  scenario: 'scenario',
};

const settings = {
  practiceLanguage: 'English',
  languageLevel: 'Intermediate',
  mode: mode.topic,
  topics: [],
  interview: {
    position: '',
    isPosition: false,
  },
  selectedTopic: '',
  maxDayFreeCost: 0.14,
  maxDayPaidCost: 0.29,
  maxDaysTrial: 3,
  maxDayFreeFeedback: 1,
};

export const userData = {
  from: {},
  premium: false,
  dayCost: 0,
  dailyCost: [],
  monthCost: 0,
  trialDays: 0,
  dayFreeFeedback: 0,
  lastPremiumDate: '',
  lastTrialDate: '',
  canWeWrite: null,
  userTextMessages: 0,
  userAudioMessages: 0,
};

export const INITIAL_SESSION = {
  messages: [],
  settings,
  lastCheckMessage: {},
  diffText: '',
  pronounce: {},
  lastResponse: '',
  lastUserMessage: '',
  pronounseScores: [],
  grammarScores: [],
  averagePronunciationScore: 0,
  averageGrammarScore: 0,
  userData,
};

export const prices = {
  'gpt-3.5-turbo-1106': {
    prompt: 0.000001,
    completion: 0.000002,
  },
  'gpt-4-1106-preview': {
    prompt: 0.00001,
    completion: 0.00003,
  },
  'whisper-1': {
    audio: 0.0001,
  },
  tts: {
    text: 0.000015,
  },
  'pronunciation-assessment': {
    audio: 0.00042,
  },
};

export const ERROR_MESSAGE = 'Ooops. Please try again or /start.';

export const topics = [
  '🤖 Future of AI',
  '🌍 Climate change',
  '🚀 Space exploration',
  '🧠 Mental health',
  '👗 Fashion and trends',
  '📱 Social media impact',
  '☀️ Renewable energy',
  '🧑‍🎓️ Education',
  '🕶️ Virtual reality',
  '🔬 Genetic engineering',
  '💰 Universal basic income',
  '💱 Cryptocurrency',
  '🔒 Online privacy',
  '🖨️ 3D printing',
  '⚕️ Medical ethics',
  '⚖️ Gender equality',
  '🤖 Robotics in healthcare',
  '🏭 Automation in industry',
  '🌱 Sustainable food',
  '💧 Water scarcity',
  '👵 Aging population',
  '🎨 Digital art',
  '🌍 Cultural diversity',
  '🚀 Space tourism',
  '🚲 Sustainable transportation',
  '♻️ Renewable resources',
  '🌿 Green technology',
  '🤖 AI in healthcare',
  '✊ Social justice',
  '🧓 Aging and technology',
  '🌍 Climate action',
  '🚀 Space colonization',
  '🧬 Biotechnology',
  '👊 Cyberbullying',
  '🚯 Plastic pollution',
  '🏢 Future of work',
  '🌾 Sustainable agriculture',
  '🌐 Internet of Things',
  '💚 Ethical consumerism',
  '🎨 AI and creativity',
  '⚖️ Environmental justice',
  '🧪 Artificial life',
  '🎓 Virtual education',
  '👨‍👩‍👧‍👦 Family',
  '✈️ Travel tales',
  '🌞 Daily life',
  '🎵 Music moments',
  '🌿 Nature wonders',
  '💡 Tech trends',
  '🏥 Health matters',
  '👧🏻 Childhood memories',
  '✈️ Dream destinations',
  '📖 Life lessons',
  '🏰 Historical events',
  '🎨 Artistic flair',
  '📱 Internet trends',
  '📺 Pop culture',
  '🗓️ Weekend plans',
  '📲 Social media',
  '🗼 Famous landmarks',
  '🥗 Healthy living',
  '💑 Relationships',
  '🚀 Future plans',
  '✈️ Travel memories',
  '🏞️ Outdoor activities',
  '🎉 Cultural fests',
  '🍽️ World cuisines',
  '🌄 Adventure stories',
  '🧘 Mindful moments',
  '💼 Dream careers',
  '♻️ Sustainable living',
  '👨‍👩‍👧‍👦 Family values',
  '✈️ Travel tales',
  '🍽️ Food adventures',
  '🎯 Hobbies and interests',
  '🌍 Cultural insights',
  '💑 Relationship tips',
  '🌟 Future aspirations',
  '🎬 Movie reviews',
  '💼 Career goals',
  '🏠 Home decor',
  '🧘‍♀️ Mind-body balance',
  '📱 Tech innovations',
  '🗣️ Language tips',
  '🐾 Pet stories',
  '🔬 Science insights',
  '🌐 Virtual travel',
  '🌊 Ocean exploration',
  '🍽️ Local cuisine',
  '🏰 Historic sites',
  '👗 Fashion trends',
  '🎥 Film classics',
  '💰 Budget travel',
  '⏰ Time management',
  '🏡 Dream home',
  '📱 Mobile apps',
  '🏛️ Ancient history',
  '🛋️ Interior design',
  '🌿 Green living',
  '📚 Online learning',
  '✊ Human rights',
  '📖 Inspiring books',
  '🌌 Astronomy facts',
  '🍔 Late night impulse',
  '🥦 Healthy eating',
  '🍳 Home cooking',
  '🍔 Street food',
  '🍬 Sweet tooth',
  '🏖️ Best vacation',
  '✈️ Travel plan',
  '🧳 Business trip',
  '👫 Friends',
  '🏃‍♂️ Athlete',
  '🌟 Celebrities',
  '👪 Parents',
  '👔 Boss',
  '💑 Partner',
  '📲 Influencer',
  '🎮 Games',
  '⚽ Sports',
  '📺 TV and movies',
  '🎵 Music',
  '🏠 Hometown',
  '👶 Childhood',
  '🐶 Pet',
  '🏡 My home',
  '👨‍👩‍👧‍👦 Family events',
  '💼 Work',
  '🛍️ Shopping',
  '🎒 School',
];
