export const topics = [
  '🤖 Future of AI',
  '🌍 Climate change',
  '🚀 Space exploration',
  '🧠 Mental health',
  '👗 Sustainable fashion',
  '📱 Social media impact',
  '☀️ Renewable energy',
  '🌎 Global education',
  '🕶️ Virtual reality',
  '🔬 Genetic engineering',
  '💰 Universal basic income',
  '💱 Cryptocurrency',
  '🔒 Online privacy',
  '🌇 Sustainable cities',
  '🖨️ 3D printing',
  '⚕️ Medical ethics',
  '⚖️ Gender equality',
  '🤖 Robotics in healthcare',
  '🏭 Automation in industry',
  '🌟 Youth empowerment',
  '🌱 Sustainable food',
  '💧 Water scarcity',
  '👵 Aging population',
  '🎨 Digital art',
  '🌍 Cultural diversity',
  '🚀 Space tourism',
  '🚲 Sustainable transportation',
  '♻️ Renewable resources',
  '🌿 Green technology',
  '🤖 AI in healthcare',
  '✊ Social justice',
  '🧓 Aging and technology',
  '🌍 Climate action',
  '🚀 Space colonization',
  '🧬 Biotechnology',
  '👊 Cyberbullying',
  '🚯 Plastic pollution',
  '🏢 Future of work',
  '🌾 Sustainable agriculture',
  '🗣️ Youth activism',
  '🌐 Internet of Things',
  '💚 Ethical consumerism',
  '🎨 AI and creativity',
  '⚖️ Environmental justice',
  '🧪 Artificial life',
  '🎓 Virtual education',
  '👨‍👩‍👧‍👦 Family bonds',
  '✈️ Travel tales',
  '🌞 Daily life',
  '🎵 Music moments',
  '🌿 Nature wonders',
  '💡 Tech trends',
  '🏥 Health matters',
  '👗 Fashion faves',
  '📚 Book buzz',
  '👧🏻 Childhood memories',
  '🍽️ Global cuisine',
  '✈️ Dream destinations',
  '📖 Life lessons',
  '🏰 Historical events',
  '🎨 Artistic flair',
  '📱 Internet trends',
  '📺 Pop culture',
  '🗓️ Weekend plans',
  '📲 Social media',
  '🗼 Famous landmarks',
  '🥗 Healthy living',
  '💑 Relationships',
  '🚀 Future plans',
  '✈️ Travel memories',
  '🏞️ Outdoor activities',
  '🎉 Cultural fests',
  '🌍🍽️ World cuisines',
  '🌄 Adventure stories',
  '🧘 Mindful moments',
  '💼 Dream careers',
  '♻️ Sustainable living',
  '👨‍👩‍👧‍👦 Family values',
  '✈️📚 Travel tales',
  '🍽️ Food adventures',
  '🎯 Hobbies and interests',
  '🌍🔍 Cultural insights',
  '💑💡 Relationship tips',
  '🌟 Future aspirations',
  '🎬 Movie reviews',
  '💼 Career goals',
  '🏠 Home decor',
  '🧘‍♀️🧠 Mind-body balance',
  '📱💡 Tech innovations',
  '🗣️ Language tips',
  '🐾 Pet stories',
  '🔬 Science insights',
  '🌐 Virtual travel',
  '🌊 Ocean exploration',
  '🍽️ Local cuisine',
  '🏰 Historic sites',
  '👗 Fashion trends',
  '🎥 Film classics',
  '💰 Budget travel',
  '⏰ Time management',
  '🏡 Dream home',
  '📱 Mobile apps',
  '🏛️ Ancient history',
  '🛋️ Interior design',
  '🌿 Green living',
  '📚 Online learning',
  '✊ Human rights',
  '📖 Inspiring books',
  '🌌 Astronomy facts',
];
